on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run cargo fmt
        env:
          TERM: xterm-256color
        run: |
          cargo fmt --all -- --check

  main:
    needs: fmt
    name: ${{ matrix.runs_on }} (clippy, test)
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: macos-latest
          - runs_on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

      - name: Run cargo test
        run: cargo test 